apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
        - name: express-backend
          image: express-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
