apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
        - name: flask-frontend
          image: flask-frontend:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_URL
              value: "http://express-backend:3000"
          ports:
            - containerPort: 5000
